### ISSUE TITLE
图表问题

### ISSUE THREAD

**Issue by ShaopengLu** [Intelligent-Computing-Lab-Yale/SATA#1]
请问这个图片是怎么显示的呢？
![Snipaste_2024-03-26_15-56-50](https://github.com/Intelligent-Computing-Lab-Yale/SATA/assets/149476790/21c4b928-de9d-4932-9496-adfa0fa523fd)

**Comment by RuokaiYin** [comment]
Hi,

Could you open another issue under this link: https://github.com/RuokaiYin/SATA_Sim

It's easier for me to track the threads there. 

Thanks.
